Print errors to stderr

diff --git a/fakepkg b/fakepkg
--- a/fakepkg
+++ b/fakepkg
@@ -26,7 +26,7 @@ function fakebuild() {
 
 	# Skip if the package already exists in the destination dir
 	if [[ -f "${2}/${PKG_NAME}.pkg.tar.${PKG_EXT}" ]]; then
-		echo -e "\e[39;1m${PKG_NAME}.pkg.tar.${PKG_EXT}\e[0m already exists in ${2}! Skipping..."
+		>&2 echo -e "\e[39;1m${PKG_NAME}.pkg.tar.${PKG_EXT}\e[0m already exists in ${2}! Skipping..."
 		return ${ERROR_USAGE}
 	fi
 
@@ -38,7 +38,7 @@ function fakebuild() {
 	if [[ -f "${PKG_DB_ENTRY}/desc" ]]; then
 		cp -a "${PKG_DB_ENTRY}/desc" pre_PKGINFO
 	else
-		echo -e "Could not find a database entry for \e[39;1m${PKG_NAME}\e[0m"
+		>&2 echo -e "Could not find a database entry for \e[39;1m${PKG_NAME}\e[0m"
 		return ${ERROR_OPERATION}
 	fi
 	[[ -f "${PKG_DB_ENTRY}/install" ]] && cp -a "${PKG_DB_ENTRY}/install" .INSTALL
@@ -90,16 +90,16 @@ function fakebuild() {
 			"${aux_files[@]}" 2>&1 >/dev/null \
 			| grep -i "permission denied" >/dev/null -; then
 
-			echo -e "The permission to open one or more directories was denied for \e[39;1m${PKG_NAME}\e[0m. The package may be incomplete!"
+			>&2 echo -e "The permission to open one or more directories was denied for \e[39;1m${PKG_NAME}\e[0m. The package may be incomplete!"
 		fi
 	fi
 
 	# Cleanup
 	if [[ -f ${PKG_NAME}.pkg.tar.${PKG_EXT} ]]; then
 		mv "${PKG_NAME}.pkg.tar.${PKG_EXT}" "$2"
-		echo -e "Reassembled \e[39;1m${PKG_NAME}\e[0m successfully!"
+		>&2 echo -e "Reassembled \e[39;1m${PKG_NAME}\e[0m successfully!"
 	else
-		echo -e "Internal \e[39;1merror\e[0m occured while processing \e[39;1m${PKG_NAME}\e[0m!"
+		>&2 echo -e "Internal \e[39;1merror\e[0m occured while processing \e[39;1m${PKG_NAME}\e[0m!"
 	fi
 	rm -rf "${TMPDIR}"
 }
@@ -168,7 +168,7 @@ done
 
 # Assembling PKG_LIST and DEST_DIR
 if ! PARAMS=$(getopt -o o:j:r:vV --long out:,jobs:,root:,verbose,version -n "$myname" -- "$@"); then
-	echo "Try '$myname --help' for more information."
+	>&2 echo "Try '$myname --help' for more information."
 	exit ${ERROR_USAGE}
 fi
 eval set -- "$PARAMS"
@@ -180,7 +180,7 @@ while true ; do
 	case "$1" in
 		-o|--out)
 		if ! DEST_DIR="$(readlink -e "$2")"; then
-			echo -e "The directory \e[39;1m$2\e[0m does not exist!"
+			>&2 echo -e "The directory \e[39;1m$2\e[0m does not exist!"
 			exit ${ERROR_USAGE}
 		fi
 		shift
@@ -190,7 +190,7 @@ while true ; do
 		if [[ $2 =~ ^-?[0-9]+$ ]]; then
 			MAX_JOBS=$2
 		else
-			echo -e "\e[39;1m$2\e[0m is not a valid integer!"
+			>&2 echo -e "\e[39;1m$2\e[0m is not a valid integer!"
 			exit ${ERROR_USAGE}
 		fi
 		shift
@@ -198,7 +198,7 @@ while true ; do
 
 		-r|--root)
 		ROOT_DIR=$2
-		[[ ! -d "${ROOT_DIR}" ]] && echo -e "The specified alternate root directory does not exist!" && exit ${ERROR_USAGE}
+		[[ ! -d "${ROOT_DIR}" ]] && >&2 echo -e "The specified alternate root directory does not exist!" && exit ${ERROR_USAGE}
 		ROOT_DIR=$(readlink -e "${ROOT_DIR}")
 		shift
 		;;
@@ -235,8 +235,8 @@ for package in "${PKG_LIST[@]}"; do
 	fi
 done
 if [[ ${#PKG_NOTFOUND} -ne 0 ]]; then
-	echo -e "The following package(s) could not be found on your system: \e[39;1m${PKG_NOTFOUND[*]}\e[0m"
-	echo -e "Keep in mind that the package(s) have to be installed!"
+	>&2 echo -e "The following package(s) could not be found on your system: \e[39;1m${PKG_NOTFOUND[*]}\e[0m"
+	>&2 echo -e "Keep in mind that the package(s) have to be installed!"
 	exit ${ERROR_USAGE}
 fi
 
