Check exit code directly instead of using "$?"

diff --git a/fakepkg b/fakepkg
--- a/fakepkg
+++ b/fakepkg
@@ -35,7 +35,12 @@ function fakebuild() {
 	cd "${TMPDIR}" || return ${ERROR_OPERATION}
 
 	# Fetching the .PKGINFO, .Changelog, .MTREE and .INSTALL file
-	[[ -f "${PKG_DB_ENTRY}/desc" ]] && cp -a "${PKG_DB_ENTRY}/desc" pre_PKGINFO || (echo -e "Could not find a database entry for \e[39;1m${PKG_NAME}\e[0m" && return ${ERROR_OPERATION})
+	if [[ -f "${PKG_DB_ENTRY}/desc" ]]; then
+		cp -a "${PKG_DB_ENTRY}/desc" pre_PKGINFO
+	else
+		echo -e "Could not find a database entry for \e[39;1m${PKG_NAME}\e[0m"
+		return ${ERROR_OPERATION}
+	fi
 	[[ -f "${PKG_DB_ENTRY}/install" ]] && cp -a "${PKG_DB_ENTRY}/install" .INSTALL
 	[[ -f "${PKG_DB_ENTRY}/mtree" ]] && gzip -dc "${PKG_DB_ENTRY}/mtree" > .MTREE
 	[[ -f "${PKG_DB_ENTRY}/changelog" ]] && cp -a "${PKG_DB_ENTRY}/changelog" .Changelog
@@ -73,11 +78,20 @@ function fakebuild() {
 	# Taring things together
 	if [[ $3 -ge "1" ]]; then
 		#XZ_OPT="-T 0" \
-		tar --ignore-failed-read --owner=0 --group=0 --no-recursion -c -a --force-local -f "${PKG_NAME}.pkg.tar.${PKG_EXT}" -C "${ROOT_DIR:-/}" -T ./package_file_list -C "$TMPDIR" "${aux_files[@]}"
+		tar --ignore-failed-read --owner=0 --group=0 --no-recursion -c -a \
+			--force-local -f "${PKG_NAME}.pkg.tar.${PKG_EXT}" \
+			-C "${ROOT_DIR:-/}" -T ./package_file_list -C "$TMPDIR" \
+			"${aux_files[@]}"
 	else
 		#XZ_OPT="-T 0" \
-		tar --ignore-failed-read --owner=0 --group=0 --no-recursion -c -a --force-local -f "${PKG_NAME}.pkg.tar.${PKG_EXT}" -C "${ROOT_DIR:-/}" -T ./package_file_list -C "$TMPDIR" "${aux_files[@]}" 2>&1 >/dev/null | grep -i "permission denied" >/dev/null
-		[[ $? -eq 0 ]] && echo -e "The permission to open one or more directories was denied for \e[39;1m${PKG_NAME}\e[0m. The package may be incomplete!"
+		if tar --ignore-failed-read --owner=0 --group=0 --no-recursion -c -a \
+			--force-local -f "${PKG_NAME}.pkg.tar.${PKG_EXT}" \
+			-C "${ROOT_DIR:-/}" -T ./package_file_list -C "$TMPDIR" \
+			"${aux_files[@]}" 2>&1 >/dev/null \
+			| grep -i "permission denied" >/dev/null -; then
+
+			echo -e "The permission to open one or more directories was denied for \e[39;1m${PKG_NAME}\e[0m. The package may be incomplete!"
+		fi
 	fi
 
 	# Cleanup
@@ -153,8 +167,10 @@ for ARG in "$@"; do
 done
 
 # Assembling PKG_LIST and DEST_DIR
-PARAMS=$(getopt -o o:j:r:vV --long out:,jobs:,root:,verbose,version -n "$myname" -- "$@")
-[[ $? -ne 0 ]] && echo "Try '$myname --help' for more information." && exit ${ERROR_USAGE}
+if ! PARAMS=$(getopt -o o:j:r:vV --long out:,jobs:,root:,verbose,version -n "$myname" -- "$@"); then
+	echo "Try '$myname --help' for more information."
+	exit ${ERROR_USAGE}
+fi
 eval set -- "$PARAMS"
 DEST_DIR=$PWD	# Default value
 VERBOSITY=0		# Default value
@@ -163,8 +179,10 @@ ROOT_DIR=""  # Default value
 while true ; do
 	case "$1" in
 		-o|--out)
-		DEST_DIR="$(readlink -e "$2")"
-		[[ $? -ne 0 ]] && echo -e "The directory \e[39;1m$2\e[0m does not exist!" && exit ${ERROR_USAGE}
+		if ! DEST_DIR="$(readlink -e "$2")"; then
+			echo -e "The directory \e[39;1m$2\e[0m does not exist!"
+			exit ${ERROR_USAGE}
+		fi
 		shift
 		;;
 
