Properly quote arrays and variables

diff --git a/fakepkg b/fakepkg
--- a/fakepkg
+++ b/fakepkg
@@ -32,7 +32,7 @@ function fakebuild() {
 
 	# Create and enter a temporary dir
 	TMPDIR=$(mktemp -q -p /tmp -t -d "${tmp_root}".XXX)
-	cd "$TMPDIR"
+	cd "${TMPDIR}" || return ${ERROR_OPERATION}
 
 	# Fetching the .PKGINFO, .Changelog, .MTREE and .INSTALL file
 	[[ -f "${PKG_DB_ENTRY}/desc" ]] && cp -a "${PKG_DB_ENTRY}/desc" pre_PKGINFO || (echo -e "Could not find a database entry for \e[39;1m${PKG_NAME}\e[0m" && return ${ERROR_OPERATION})
@@ -45,7 +45,7 @@ function fakebuild() {
 	sed -i '/^$/d' pre_PKGINFO
 	while read line; do
 		if [[ $line =~ %[A-Z]+% ]]; then
-			PKG_VAR=$(echo ${line,,} | tr -d '%')
+			PKG_VAR=$(echo "${line,,}" | tr -d '%')
 			case "$PKG_VAR" in
 				"name")     PKG_VAR=pkgname;;
 				"version")  PKG_VAR=pkgver;;
@@ -82,12 +82,12 @@ function fakebuild() {
 
 	# Cleanup
 	if [[ -f ${PKG_NAME}.pkg.tar.${PKG_EXT} ]]; then
-		mv ${PKG_NAME}.pkg.tar.${PKG_EXT} $2
+		mv "${PKG_NAME}.pkg.tar.${PKG_EXT}" "$2"
 		echo -e "Reassembled \e[39;1m${PKG_NAME}\e[0m successfully!"
 	else
 		echo -e "Internal \e[39;1merror\e[0m occured while processing \e[39;1m${PKG_NAME}\e[0m!"
 	fi
-	rm -rf $TMPDIR
+	rm -rf "${TMPDIR}"
 }
 
 # Run fakebuild in parallel with a limit of $MAX_JOBS jobs
@@ -95,7 +95,7 @@ function fakebuild() {
 MAX_JOBS=1
 function parallelize() {
 	while [[ $# -gt 0 ]] ; do
-		job_count=($(jobs -p))
+		mapfile -t job_count < <(jobs -p)
 		if [[ ${#job_count[@]} -lt $MAX_JOBS ]] ; then
 			fakebuild "$1" "$DEST_DIR" "$VERBOSITY" &
 			shift
@@ -163,7 +163,7 @@ ROOT_DIR=""  # Default value
 while true ; do
 	case "$1" in
 		-o|--out)
-		DEST_DIR="$(readlink -e $2)"
+		DEST_DIR="$(readlink -e "$2")"
 		[[ $? -ne 0 ]] && echo -e "The directory \e[39;1m$2\e[0m does not exist!" && exit ${ERROR_USAGE}
 		shift
 		;;
@@ -206,7 +206,7 @@ while true ; do
 	esac
 	shift
 done
-PKG_LIST=($*)
+PKG_LIST=("$@")
 
 # Checking the PKG_LIST
 [[ ${#PKG_LIST[@]} == 0 ]] && usage && exit ${ERROR_USAGE}
@@ -217,16 +217,12 @@ for package in "${PKG_LIST[@]}"; do
 	fi
 done
 if [[ ${#PKG_NOTFOUND} -ne 0 ]]; then
-	echo -e "The following package(s) could not be found on your system: \e[39;1m${PKG_NOTFOUND[@]}\e[0m"
+	echo -e "The following package(s) could not be found on your system: \e[39;1m${PKG_NOTFOUND[*]}\e[0m"
 	echo -e "Keep in mind that the package(s) have to be installed!"
 	exit ${ERROR_USAGE}
 fi
 
 # Assembling the packages
-if [[ $MAX_JOBS -gt "1" ]]; then
-	parallelize "${PKG_LIST[@]}"
-else
-	for PKG in ${PKG_LIST[@]}; do fakebuild $PKG "$DEST_DIR" "$VERBOSITY"; done
-fi
+parallelize "${PKG_LIST[@]}"
 
 exit 0
